Main_Folder_Tik_Tok/urls.py
from django.contrib import admin
from django.contrib.auth import views as auth_views
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static
from companies_app import views as companies_views

urlpatterns = [        #url configuration
    path('admin/', admin.site.urls),
    path('', include('main_app.urls')),
    path('companies/', include('companies_app.urls')),
    path('calendar_app/', include('calendar_app.urls')),
    path('user/',include('users.urls')),
]

calendar_app/urls.py
from django.conf.urls import url
from . import views

app_name = 'calendar_app'
urlpatterns = [
    url(r'^index/$', views.index, name='index'),
    url(r'^calendar/$', views.CalendarView.as_view(), name='calendar'),
    url(r'^event/new/$', views.event, name='event_new'),
	url(r'^event/edit/(?P<event_id>\d+)/$', views.event, name='event_edit'),
]

companies_app/urls.py
from django.contrib import admin
from django.contrib.auth import views as auth_views
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static
from companies_app import views as companies_views

app_name = 'companies_app'
urlpatterns = [   
    
    path('<int:company_id>/',companies_views.etrafli, name = 'etrafli'),
]

users/urls.py
from django.urls import path
from django.contrib.auth import views as auth_views
from django.conf.urls.static import static
from users import views as user_views

urlpatterns = [
    path('register/', user_views.register, name='register'),
    path('profile/', user_views.profile, name='profile'),
    path('login/', auth_views.LoginView.as_view(template_name='users/login.html'), name='login'),
    path('logout/', auth_views.LogoutView.as_view(template_name='users/logout.html'), name='logout'),
    path('password-reset/',
         auth_views.PasswordResetView.as_view(
             template_name='users/password_reset.html'
         ),
         name='password_reset'),
    path('password-reset/done/',
         auth_views.PasswordResetDoneView.as_view(
             template_name='users/password_reset_done.html'
         ),
         name='password_reset_done'),
    path('password-reset-confirm/<uidb64>/<token>/',
         auth_views.PasswordResetConfirmView.as_view(
             template_name='users/password_reset_confirm.html'
         ),
         name='password_reset_confirm'),
    path('password-reset-complete/',
         auth_views.PasswordResetCompleteView.as_view(
             template_name='users/password_reset_complete.html'
         ),
         name='password_reset_complete'),
    
]

companies_app/models.py
from django.db import models
from phonenumber_field.modelfields import PhoneNumberField
from multiselectfield import MultiSelectField
from django.utils.translation import gettext_lazy as _



from django.urls import reverse


# Create your models here.
class Services(models.Model):  #Service for example: yaglamag,moyka
    service_name = models.CharField(max_length=255)

    def __str__(self):
        return f"{self.service_name}"

class Company(models.Model):    #Company Model
    company_id = models.IntegerField(unique=True,primary_key=True)
    company_name = models.CharField(("Service_name"),help_text="Servisin adını daxil edin",
    unique=True, max_length=250)
    company_latitude = models.FloatField(
        ("Service Latitude"), help_text="koordinati daxil edin")
    company_longitude = models.FloatField(
        ("Company Longitude"), help_text="koordinati daxil edin")
    adress = models.CharField(("Adress"), help_text = 'Servisin ünvanını daxil edin',max_length=250)
    email = models.EmailField(("Email"), help_text = 'Servisin email adresini daxil edin',max_length=254)
    phone_number = PhoneNumberField(max_length=13, null=False, verbose_name="Phone number", help_text="Servisin əlaqə nömrəsini daxil edin")
    categories = models.ManyToManyField(Services)
    

    
    def __str__(self):
        return "{},{},{},{},{}".format(self.company_id,self.company_name,self.adress,self.email,self.phone_number)

    class Meta:
        verbose_name = "Company"
        verbose_name_plural = "Companies"
        ordering = ["-company_id"]

companies_app/views.py
from django.shortcuts import render,get_object_or_404
from companies_app.models import Company
from calendar_app.views import get_date,prev_month,next_month
from datetime import datetime, timedelta, date
from django.shortcuts import render, get_object_or_404
from django.http import HttpResponse, HttpResponseRedirect
from django.views import generic
from django.urls import reverse
from django.utils.safestring import mark_safe
import calendar
from calendar_app.utils import Calendar
from calendar_app.forms import EventForm

# Create your views here.
def etrafli(request,company_id):

    context = {}
    company  = get_object_or_404(Company, company_id = company_id)
    context["company"] = company
    item = company
    # ''' device locakitino''''
    result = []
    
    new_data = Company.objects.get(
    company_id=item.company_id)
    result.append({
        "company_id": item.company_id,
        "coords": {"lat": item.company_latitude, "lng": item.company_longitude},
        "text": "Cihaz no: {} ".format(item.company_id),
        "company_name": "Servis name: {} ".format(item.company_name),
                
    })
    # except Company.DoesNotExist:
    #     pass
    context["object_list"] = result
    
    d = get_date(request.GET.get('month', None))
    cal = Calendar(d.year, d.month)
    html_cal = cal.formatmonth(withyear=True,comp_id = company_id)
    context['calendar'] = mark_safe(html_cal)
    context['prev_month'] = prev_month(d)
    context['next_month'] = next_month(d)
    return render(request, "companies_app/company.html", context)

companies_app/templates/companies_app/company.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <title>Document</title>
</head>
<body>

    <h1>Company</h1>
    
    <p>{{company.company_id}}</p>
    <p>{{company.company_name}}</p>
    <p>{{company.adress}}</p>
    <p>{{company.email}}</p>
    <p>{{company.phone_number}}</p>

    <div class="container-fluid">
        <div class="row">
            <div class="col-lg-10 col-md-10 col-sm-10 col-xs-12">
                <div id="map" style="width: 100%; height: 500px;"></div>
            </div>
        </div>
    </div>
   


        <script>
            var cordinates = [];



            function initMap(target = false) {
                //Map options
                var options;
                if (target) {
                    options = {
                        zoom: 5,
                        center: target
                    }
                }
                else {
                    options = {
                        zoom: 12,
                        center: { lat: 40.4109471, lng: 49.8681077 }
                    }
                }

                //New map
                var map = new google.maps.Map(document.getElementById('map'), options);

                //Add marker
                var marker = new google.maps.Marker({
                    // position: { lat: 40.4109471, lng: 49.8681077 },
                    map: map,
                    title: "Cihaz ID: {{ company_id }} ",
                    icon: "{%  static 'home_app/images/marker.png' %}"
                });

                marker.addListener('mouseover', function () {   
                    infoWindow.open(map, marker);
                });

                {% for obj in object_list %}
                    {% if obj.company_id == company.company_id %}
                    var infoWindow{{forloop.counter}} = new google.maps.InfoWindow({
                      
                       content: '<form method="get", action="{% url "companies_app:etrafli" obj.company_id %}">    <label for="exampleFormControlSelect1">{{obj.company_name}} {{obj.company_id}}</label> <button  type="submit" class="btn btn-success btn-sm btn-block">Etrafli</button> </form>'               
                    });
                    addMarker({{ obj.coords | safe }}, '{{ obj.text }}', "{{ obj.device_icon}}", infoWindow{{forloop.counter}});
                    cordinates.push({
                        "name": '{{ obj.text }}',
                        "data": {{ obj.coords | safe }},
                        "icon": "{{ obj.device_icon}}",
                        
                        })
                    {% endif %}
                {% endfor %}

                object_list

            
            
            // Add Marker function
            function addMarker(coords, text, device_icon, new_info) {
                var marker = new google.maps.Marker({
                    position: coords,
                    map: map,
                    // title: "Cihaz ID: {{ text }} ",
                    icon: device_icon,
                });
              
                
            }
            
             

           

            }
        </script>
        <script async defer
     
            src="https://maps.googleapis.com/maps/api/js?key=AIzaSyAzjnO5f_DJlfKjOxgZ2PO7FEDTCMkDIiM&callback=initMap"></script>
        <script src="https://code.jquery.com/jquery-3.3.1.slim.min.js"
            integrity="sha384-q8i/X+965DzO0rT7abK41JStQIAqVgRVzpbzo5smXKp4YfRvH+8abtTE1Pi6jizo"
            crossorigin="anonymous"></script>
        <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.7/umd/popper.min.js"
            integrity="sha384-UO2eT0CpHqdSJQ6hJty5KVphtPhzWj9WO1clHTMGa3JDZwrnQq4sF86dIHNDz0W1"
            crossorigin="anonymous"></script>
        <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/js/bootstrap.min.js"
            integrity="sha384-JjSmVgyd0p3pXB1rRibZUAYoIIy6OrQ6VrjIEaFf/nJGzIxFDsf4x0xIM+B07jRM"
            crossorigin="anonymous"></script>
<link rel="stylesheet" type="text/css" href="{% static 'calendar_app/css/styles.css' %}">

    <div class="clearfix">
	<a class="btn btn-info left" href="{% url 'calendar_app:calendar' %}?{{ prev_month }}"> Previous Month </a>
	<a class="btn btn-info right" href="{% url 'calendar_app:calendar' %}?{{ next_month }}"> Next Month </a>
	<a class="btn btn-info right" href="{% url 'calendar_app:event_new' %}"> New Event </a>
    </div>


    {{calendar}}
</body>
</html>